# Generated by Django 3.2 on 2021-04-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210417_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
